# Generated by Django 5.1 on 2024-08-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0002_alter_material_options_alter_material_patrimonio'),
        ('policial', '0005_alter_policial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('opcao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('alteracao', models.TextField(blank=True, null=True)),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautela_entregador', to='policial.policial')),
                ('furriel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautela_furriel', to='policial.policial')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='material.material')),
                ('recebedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cautela_recebedor', to='policial.policial')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautela_solicitante', to='policial.policial')),
            ],
        ),
    ]
