# Generated by Django 5.1 on 2024-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
