# Generated by Django 5.1 on 2024-08-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautela', '0002_alter_cautela_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cautela',
            name='status',
            field=models.CharField(choices=[('aberto', 'Em aberto'), ('fechado', 'Fechado')], default='aberto', max_length=7),
        ),
    ]
