# Generated by Django 5.1 on 2024-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautela', '0003_cautela_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
