# Generated by Django 5.1 on 2024-08-28 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cautela', '0004_alter_cautela_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cautela',
            name='data_entrega',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
