# Generated by Django 5.1 on 2024-08-08 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('nome_guerra', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)])),
                ('post_grad', models.CharField(choices=[('SD', 'Soldado'), ('CB', 'Cabo'), ('3SGT', '3º Sargento'), ('2SGT', '2º Sargento'), ('1SGT', '1º Sargento'), ('ST', 'Subtenente'), ('ASP', 'Aspirante'), ('TEN', 'Tenente'), ('CAP', 'Capitão'), ('MAJ', 'Major'), ('TC', 'Tenente-Coronel'), ('CEL', 'Coronel')], default='SD', max_length=5)),
            ],
        ),
    ]
