# Generated by Django 5.1 on 2024-08-12 16:53

import policial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0002_policial_created_at_policial_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='cpf',
            field=models.CharField(help_text='Digite um CPF válido.', max_length=11, unique=True, validators=[policial.models.validate_cpf]),
        ),
    ]
