# Generated by Django 5.1 on 2024-08-12 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0004_alter_policial_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policial',
            options={'ordering': ['post_grad']},
        ),
    ]
