# Generated by Django 5.1 on 2024-08-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0005_alter_policial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
